### ISSUE TITLE
Pressing "pair" should validate the pairing, confirm, and remove both users from available set

### ISSUE THREAD

**Issue by henrytsai** [yasyf/hifromtheotherside#14]
The example: I matched a Chloe (Clinton) with a Rachel (Trump), pressed "pair", but I wasn't sure if it logged in the system that the two are now paired. Afterwards, the two users should be removed from total set (meaning they shouldn't be suggested anymore).

**Comment by yasyf** [comment]
@henrytsai this already happens just not in the UI
