### ISSUE TITLE
Automate email template

### ISSUE THREAD

**Issue by henrytsai** [yasyf/hifromtheotherside#16]
I send this from inbox.google.com. This is the current template, but happy to adjust if the timezone/zipcode lookup is too hard.

-----

SUBJECT: 
Your "Hi From The Other Side" Match!

Hi [USER 1] and [USER 2],

Thanks for taking the time to have a conversation. I'll leave it up to you two to find a time for

[IF NOT SAME CITY]: a video chat or a call – one of you is in the ______ time zone and the other is in the _____ time zone. We highly recommend a video chat though!

[IF NOT SAME CITY BUT SAME TIME ZONE] a video chat or a call – both of you are in the _____ time zone. We highly recommend a video chat though!

[IF SAME CITY]: a video chat or even in person conversation – both of you are in or near [CITY NAME].

Here's a conversation guide I put together to get you started: <a href='https://www.hifromtheotherside.com/guide>Conversation Guide</a>. 

I'll follow up in a week to see how it went. Thanks!

Henry

--
Henry Tsai
henry@hifromtheotherside.com

**Comment by yasyf** [comment]
@henrytsai need email creds before I can set this up
