### ISSUE TITLE
Dashboard: add search parameter by zipcode

### ISSUE THREAD

**Issue by henrytsai** [yasyf/hifromtheotherside#31]
Better if it's a range of zipcodes, for example I currently need to find someone who lives in LA

**Comment by duncanka** [comment]
I'm assuming that the ideal would be to find everyone within, say, 25 miles of a given zip code?

If so, that's surprisingly difficult to do. The two natural ways to do this are:
1. Find a list of all zip codes within the desired radius of the requested code, and only return users with one of those zip codes.
2. Geocode every user's zip code. When searching, geocode the requested zip and return users with lat/lon within the desired radius.

Option 1 requires finding a database of zip codes (with lat/lon data) that we save and query. http://simplemaps.com/data/us-zips seems to be a good one, but requires attribution.

Option 2 requires using a geocoding API. Unfortunately, the more popular APIs explicitly forbid storing the returned geolocation data, so caching the results for searching might be off-limits.

The easiest thing to do is actually just to search based on the first 3 digits of the zip code. These digits typically refer to a postal delivery area. In metropolitan areas, these are typically pretty local, which may exclude nearby results that happen to be just outside the delivery area (e.g., Santa Monica and Beverly Hills have distinct 3-digit codes from LA). In rural areas, these can be huge, which may produce artificial matches (e.g., 5 codes cover most of Nebraska). But it's a bit better than exact zip code matching.

Which option would you prefer?
