### ISSUE TITLE
Build matching algo

### ISSUE THREAD

**Issue by henrytsai** [yasyf/hifromtheotherside#7]
"For matching, very basic would just be to iterate through each unmatched user. For each one, get the type they desire, and find the first unmatched user of that type (if any exist), and pair them. We’ll have to create a new model for a Pairing, which belongs to both users. Getting fancy involves mailchimp integration and auto-emailing matches."

**Comment by yasyf** [comment]
Closed by ba56705e25c496ec12e286ccc38eec58e9440173.
